### ISSUE TITLE
App Store Bug [ONEOS 2.0 PUBLIC BETA]

### ISSUE THREAD

**Issue by supertassu** [oeed/OneOS#331]
The app store not works. 
![SCREENSHOT](https://cloud.githubusercontent.com/assets/9721638/6555954/9b36e7fe-c672-11e4-90b0-77597d9e4002.png)
Can you fix it?

**Comment by Nightpaw** [comment]
It might have been caused because of your emulator.

**Comment by officalredcreeper** [comment]
I checked the website and if im right/wrong, the domain (website itself) was deleted and the domain name was released and was took over. If you dont believe me, go to ccappstore.com and you'll see

**Comment by supertassu** [comment]
+officalredcreeper The cc app store is moved to appstore.olivercooper.me and the app uses it.
