### ISSUE TITLE
Shell Startup Error

### ISSUE THREAD

**Issue by alexp9982** [oeed/OneOS#334]
![2015-07-01_10 43 42](https://cloud.githubusercontent.com/assets/13136926/8457497/b4600b2c-1fdf-11e5-89b8-f8c31cbb7883.png)

When running startup program in shell on OneOS

**Comment by haddockdev** [comment]
It's because of the way OneOS sandboxes.
If you want it to work, you can:

1. put all files into a folder with ".program" (ex "OneOS.program")
2. modify the startup file to use OneOS.FS instead of fs

Plus, you will not be getting any support because this project is long dead.
